### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by CertifiedRice** [FreakC-Foundation/FreakC#4]
Batchfile only has Windows(7-10) support. There needs to be support for Linux. Turning everything into Bash(shell) would be good and will allow support for Linux operating systems.

**Comment by nguyenphuminh** [comment]
Thanks for the suggestion, I'm actually trying to port it to Linux. But for now, I guess you can use Wine to run Batch scripts.

**Comment by JavaCode7** [comment]
It is a good idea that I have asked @nguyenphuminh to do in the past. I think it would be cool.

**Comment by nguyenphuminh** [comment]
There would be problems though, since FreakC was meant to be a superset of Batch, so it's very easy to implement it on Windows. Porting it to Linux means that I both need to make a new codebase and implement a new compilation target, but I guess I'll try

**Comment by nguyenphuminh** [comment]
I think it would be better not to use Bash to make the compiler, but rather use other "more popular" languages. But the compilation target would be Bash.
