### ISSUE TITLE
uhhh

### ISSUE THREAD

**Issue by CertifiedRice** [FreakC-Foundation/FreakC#5]
Idk what to say about [this file](https://github.com/FreakC-Foundation/FreakC/blob/master/Source/FCShell.bat)
wouldn't really use this in an actual project lol,

**Comment by nguyenphuminh** [comment]
Just a crappy feature for someone who likes typing in the console really :v

**Comment by CertifiedRice** [comment]
but why add cussing lol?

**Comment by nguyenphuminh** [comment]
Like I have said, it's for people who ought to use write small programs right in their console...
